array_width = 100
attr_fn_like_width = 100
binop_separator = "Front" # default
#blank_lines_lower_bound = 0 # default
#blank_lines_upper_bound = 1 # default
brace_style = "PreferSameLine"
chain_width = 100
#color = "Auto" # default
combine_control_expr = false
comment_width = 100
condense_wildcard_suffixes = true
control_brace_style = "ClosingNextLine"
#disable_all_formatting = false # default
doc_comment_code_block_width = 100 # default # req. `format_code_in_doc_comments = true`
edition = "2021"
#empty_item_single_line = true # default
#enum_discrim_align_threshold = 0 # default
#error_on_line_overflow = false # default
#error_on_unformatted = false # default
#fn_args_layout = "Tall" # default
fn_call_width = 100
fn_single_line = true
#force_explicit_abi = true # default
#force_multiline_blocks = false # default
format_code_in_doc_comments = true
#format_generated_files = true # default
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
#hard_tabs = false # default
group_imports = "StdExternalCrate"
hex_literal_case = "Lower"
#hide_parse_errors = false # default
#ignore = ["some/example_file.rs",] # default: empty list
imports_indent = "Visual"
#imports_layout = "Mixed" # default
imports_granularity = "Crate"
indent_style = "Visual"
#inline_attribute_width = 0 # default
#match_arm_blocks = true # default
#match_arm_leading_pipes = "Never" # default
match_block_trailing_comma = true
max_width = 100
#merge_derives = true # default
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
#overflow_delimited_expr = false # default
#remove_nested_parens = true # default
reorder_impl_items = true
#reorder_imports = true # default
reorder_modules = true
#required_version = "1.5.1" # example; current as of time of writing
#short_array_element_width_threshold = 10 # default
#skip_children = false # default
# single_line_if_else_max_width = 50 # default
#space_after_colon = true # default
#space_before_colon = false # default
#spaces_around_ranges = false # default
#struct_field_align_threshold = 0 # default
#struct_lit_single_line = true # default
#struct_lit_width = 18 # default
#struct_variant_width = 50 # default
#tab_spaces = 4 # default
trailing_comma = "Always"
trailing_semicolon = true
#type_punctuation_density = "Wide" # default
unstable_features = true
use_field_init_shorthand = true
#use_small_heuristics = "Default" # default
use_try_shorthand = true
where_single_line = true
wrap_comments = true
